# Generated by Django 4.2.16 on 2026-03-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idcard_app', '0006_biometrickey_client_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Leave blank to send to ALL students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='idcard_app.batch'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive announcements are hidden from students'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='distance_m',
            field=models.FloatField(default=0, help_text='Distance from location center in meters'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(help_text='Student GPS latitude at mark time'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(help_text='Student GPS longitude at mark time'),
        ),
        migrations.AlterField(
            model_name='attendancelocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancelocation',
            name='latitude',
            field=models.FloatField(help_text='GPS latitude of the location center'),
        ),
        migrations.AlterField(
            model_name='attendancelocation',
            name='longitude',
            field=models.FloatField(help_text='GPS longitude of the location center'),
        ),
        migrations.AlterField(
            model_name='attendancelocation',
            name='name',
            field=models.CharField(help_text='e.g. Main Building, Computer Lab', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancelocation',
            name='radius_meters',
            field=models.PositiveIntegerField(default=50, help_text='Allowed radius in meters'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(help_text='e.g. P4-KV, J5-AM', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='timing',
            field=models.CharField(blank=True, help_text='e.g. 6:00 AM - 7:30 AM', max_length=100),
        ),
        migrations.AlterField(
            model_name='biometrickey',
            name='credential_id',
            field=models.TextField(help_text='WebAuthn credential ID (base64url)', unique=True),
        ),
        migrations.AlterField(
            model_name='biometrickey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='biometrickey',
            name='public_key',
            field=models.TextField(help_text='WebAuthn attestationObject (base64url) from registration'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='batch',
            field=models.ForeignKey(help_text='Which batch this class belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='idcard_app.batch'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Day this schedule repeats every week'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(help_text='Class end time'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='location',
            field=models.ForeignKey(help_text='Building / Lab where class is held', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='idcard_app.attendancelocation'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(help_text='Class start time'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='subject',
            field=models.CharField(help_text='e.g. Python Basics, Django Framework', max_length=200),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Faculty teaching this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='idcard_app.faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 6 months, 1 year', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idcardrequest',
            name='course_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduleattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
